<a href="https://colab.research.google.com/github/yanliu1111/youtube-rag-main/blob/main/Python_colab_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import nn #import torch.nn as nn

In [2]:
x = 5
y = 6
x, y = 5, 6
x

5

In [3]:
def add_mult_2 (a, b):
    return 2*(a + b)

In [4]:
z = add_mult_2(7,8)
print(z)

30


In [5]:
class Net(nn.Module):
    def __init__(self, input_sz=1):
        super(Net, self).__init__()
        self.layer = nn.Linear(input_sz, 1)
        self.input_sz = input_sz

    def forward(self,x):
        x = self.layer(x)
        return x

In [6]:
model = Net(input_sz = 10)

In [8]:
model2 = Net( )

In [9]:
model2.input_sz

1

In [10]:
input = torch.tensor(2.).unsqueeze(0)
input

tensor([2.])

In [11]:
model2.forward(input)

tensor([-1.4546], grad_fn=<ViewBackward0>)

In [12]:
model2(input)

tensor([-1.4546], grad_fn=<ViewBackward0>)

In [13]:
for i in range(5):
    print (i)

0
1
2
3
4


In [14]:
if (i < 2):
    print ('yes')
else:
    print('no')

no
